apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.secretName }}
spec:
  secretName: {{ .Values.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.issuerName }}
  commonName: "{{ .Values.commonName }}"
  duration: 2160h
  renewBefore: 360h
  dnsNames:
  - "{{ .Values.domainName }}"
