apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wallet-service-nodejs.fullname" . }}
  labels:
    app: {{ template "wallet-service-nodejs.name" . }}
    chart: {{ template "wallet-service-nodejs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "wallet-service-nodejs.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "wallet-service-nodejs.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "wallet-service-nodejs.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
      {{- with .Values.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
      {{- end }}
      {{- with .Values.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
      {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
