apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "cassandra.fullname" . }}-backup-service-account
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
    credentials.json: {{ .Values.backup.SealedSecret | quote }}
  template:
    metadata:
      name: {{ template "cassandra.fullname" . }}-backup-service-account
      namespace: cassandra
    type: Opaque
