apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.certIssuer }}
spec:
  acme:
    # The ACME production server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: cr.jitender@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.certIssuer }}
    # Enable the DNS-01 challenge provider
    solvers:
    - dns01:
        azuredns:
          # Service principal clientId (also called appId)
          clientID: f7533776-193a-4efd-8165-44a7edb4621d
          # A secretKeyRef to a service principal ClientSecret (password)
          # ref: https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-kubernetes-service-principal
          clientSecretSecretRef:
            name: azuredns-config
            key: CLIENT_SECRET
          # Azure subscription Id
          subscriptionID: 24901274-4261-4c4e-b381-e33d66de3534
          # Azure AD tenant Id
          tenantID: 9b6736d1-ecf7-470e-bdfd-bbcbb1da053d
          # ResourceGroup name where dns zone is provisioned
          resourceGroupName: comrate-prod
          hostedZoneName: comrate.com
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud